export const SET_LOGIN_USERNAME = 'LOGIN_USERNAME';
export const ADD_API_DATA = 'ADD_API_DATA';
export const ADD_API_ROOM_DATA = 'ADD_API_ROOM_DATA';
export const SET_LOCA_ROOM_DATA = 'SET_LOCA_ROOM_DATA';
